### ISSUE TITLE
Panel doesn't show up

### ISSUE THREAD

**Issue by nan0m** [MrWalkmanDev/AdaptiSound#2]
On Adapti Sound release 0.2, on the demo project. 
Godot 4.1 stable, Windows 10, RTX3070

The AdaptiSound panel won't open.
Reloading the project seems to fix the issue
![image](https://github.com/MrWalkmanDev/AdaptiSound/assets/74869542/ea2328bc-9972-4336-84f6-2eb0913d7de7)

**Comment by MrWalkmanDev** [comment]
Hi there, when installing the plugin for the first time, errors may appear, but as you say, they should be resolved when reopening the project. If not, I'll have to check it out 😅.
