### ISSUE TITLE
Working fine in editor, but not finding any directory or files once exported

### ISSUE THREAD

**Issue by Hiasae** [MrWalkmanDev/AdaptiSound#3]
As title, the exported project doesn`t find any files and not directory.

**Comment by MrWalkmanDev** [comment]
Hi!,
Which version of the plugin are you using? version 0.1 has that problem, but version 0.3 shouldn't.

If you downloaded the plugin from the Asset Library, it is likely that you have version 0.1, I just checked that I did not update it in Asset Library (by tomorrow it should be updated)

**Comment by Hiasae** [comment]
Yes, you are correct. Thanks for the response and the amazing tool. 👍
