### ISSUE TITLE
File conflicts on install

### ISSUE THREAD

**Issue by 2fd5** [MrWalkmanDev/AdaptiSound#4]
Hi, 

Upon installation of the plugin I got some conflicts, as you plugin install some files to the root of my project

![image](https://github.com/MrWalkmanDev/AdaptiSound/assets/64538990/61ddf8e5-4cad-4de4-be02-d13476cd2b75)

I would expect for player to install only files in its `addons/` folder

It is not a big issue as I can deselect what I don't need.

Thanks for making and sharing the plugin. Will save a lot of work

**Comment by MrWalkmanDev** [comment]
Hi!, you're right, I'm going to update the project so that everything is organized inside the Addons folder. Thank you!
